//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internet_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_goods
    {
        public string name_product { get; set; }
        public int order_number { get; set; }
        public int id { get; set; }
        public string name_option { get; set; }
        public int global_id { get; set; }
    
        public virtual t_order t_order { get; set; }
    }
}
