//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internet_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_option
    {
        public int Id { get; set; }
        public int id_product { get; set; }
        public string option_name { get; set; }
        public int option_price { get; set; }
    
        public virtual t_product t_product { get; set; }
    }
}
