//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internet_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_order
    {
        public t_order()
        {
            this.t_goods = new HashSet<t_goods>();
        }
    
        public int order_number { get; set; }
        public System.DateTime date_order { get; set; }
        public string manager_order { get; set; }
        public string contact_data { get; set; }
        public string comment { get; set; }
        public string adress { get; set; }
    
        public virtual ICollection<t_goods> t_goods { get; set; }
    }
}
