//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internet_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_product
    {
        public t_product()
        {
            this.t_option = new HashSet<t_option>();
        }
    
        public int Id { get; set; }
        public string product_name { get; set; }
        public int product_price { get; set; }
    
        public virtual ICollection<t_option> t_option { get; set; }
    }
}
